services:
  mariadb:
    image: mariadb:10.6
    container_name: etrade_mariadb

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e_trade
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # bind mount để lưu dữ liệu bền vững ở thư mục host, khác với volume mặc định của Docker không nên truy cập trực tiếp từ host
    networks:
      - etrade-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: etrade_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mariadb
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: remy4657/etrade-backend:latest
    container_name: etrade_backend
    environment:
      SPRING_APPLICATION_NAME: shop
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/e_trade
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root # mat khau giong mat khau tren mysql
    ports:
      - "8080:8080" # trên local sẽ truy cập backend qua cổng 8080, bên trong container sẽ chạy trên cổng 8080
    networks:
      - etrade-network
networks:
  etrade-network:
    external: true
volumes:
  db_data:
